# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  hiptest_publisher:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.3-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: update features files with hiptest-publisher
          command: |
            echo 'export PATH=$PATH:.'
            gem install hiptest-publisher
            hiptest-publisher --token $SECRET_TOKEN -c rspec.conf --test-run-id=243901 --only=tests
          environment:
            SECRET_TOKEN: 24217329994854315832799885021744245684935169348830984566

      # run tests!
      - run:
          name: run tests
          command:
            bundle exec rspec --format RspecJunitFormatter -o report.xml

  push results:
      - run:
          name: push tests results file
          command:
            hiptest-publisher -c rspec.conf --token=$SECRET_TOKEN --push=report.xml --test-run-id=243901
          environment:
            SECRET_TOKEN: 24217329994854315832799885021744245684935169348830984566
workflows:
  version: 2
  example_jobs:
    jobs:
      - hiptest-publisher
      - push results:
          requires:
<<<<<<< HEAD
            - hiptest-publisher
=======
            - hiptest-publisher
>>>>>>> e7ecafb1c1b2d947bd0500c6e410642db6ff7e24
